const ENCOUNTER_STATUSES = {
  REGISTERED: 'registered',
  WAITING: 'waiting',
  IN_CONSULTATION: 'in_consultation',
  CONSULTATION_COMPLETED: 'consultation_completed',
  CONFIRMATION_PENDING: 'confirmation_pending',
  CONFIRMED_TABLET: 'confirmed_tablet',
  CONFIRMED_SMS: 'confirmed_sms',
  CONFIRMATION_NOT_RECEIVED: 'confirmation_not_received',
  PATIENT_DISPUTED: 'patient_disputed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
};

const CONFIRMABLE_FROM = new Set([
  ENCOUNTER_STATUSES.CONSULTATION_COMPLETED,
  ENCOUNTER_STATUSES.CONFIRMATION_PENDING,
]);

function canTransition(from, to) {
  const allowed = {
    [ENCOUNTER_STATUSES.REGISTERED]: [ENCOUNTER_STATUSES.WAITING, ENCOUNTER_STATUSES.CANCELLED],
    [ENCOUNTER_STATUSES.WAITING]: [
      ENCOUNTER_STATUSES.IN_CONSULTATION,
      ENCOUNTER_STATUSES.NO_SHOW,
      ENCOUNTER_STATUSES.CANCELLED,
    ],
    [ENCOUNTER_STATUSES.IN_CONSULTATION]: [
      ENCOUNTER_STATUSES.CONSULTATION_COMPLETED,
      ENCOUNTER_STATUSES.CANCELLED,
    ],
    [ENCOUNTER_STATUSES.CONSULTATION_COMPLETED]: [
      ENCOUNTER_STATUSES.CONFIRMATION_PENDING,
      ENCOUNTER_STATUSES.CONFIRMED_TABLET,
      ENCOUNTER_STATUSES.CONFIRMED_SMS,
      ENCOUNTER_STATUSES.PATIENT_DISPUTED,
      ENCOUNTER_STATUSES.CONFIRMATION_NOT_RECEIVED,
    ],
    [ENCOUNTER_STATUSES.CONFIRMATION_PENDING]: [
      ENCOUNTER_STATUSES.CONFIRMED_TABLET,
      ENCOUNTER_STATUSES.CONFIRMED_SMS,
      ENCOUNTER_STATUSES.PATIENT_DISPUTED,
      ENCOUNTER_STATUSES.CONFIRMATION_NOT_RECEIVED,
    ],
  };
  return (allowed[from] || []).includes(to);
}

module.exports = { ENCOUNTER_STATUSES, CONFIRMABLE_FROM, canTransition };
